import { useEffect, useRef, useState } from "react";
import { t, type Language } from "../../i18n";
import { EVENT } from "../../lib/event";
import { useCountdown } from "../../lib/countdown";
import { haptics } from "../../lib/haptics";
import { prefersReducedMotion, useMagnetic, useScrollY } from "../../lib/motion";
import { useCountUp } from "../../lib/useCountUp";
import { play, unlockAudio } from "../../lib/sound";
import type { LiveStats } from "../../lib/live";
import { Icon } from "./Icons";
import { Reveal, RevealWords } from "./Reveal";

interface HeroEditorialProps {
  language: Language;
  onPrimary: () => void;
  onSecondary: () => void;
  stats: LiveStats | null;
}

/**
 * Editorial B2B hero — deep navy + warm gold, asymmetric, one confident
 * headline, dual CTA.
 *
 * What makes it feel *alive* rather than a mock-up:
 *   - the art is parallaxed against the scroll and slowly breathing,
 *   - the headline is written in word by word,
 *   - the countdown carries real seconds that flip on change, so the block is
 *     visibly a clock and not a picture of one,
 *   - the booth counter underneath the CTAs is read from the database, not
 *     typed into a slide deck.
 */
export function HeroEditorial({ language, onPrimary, onSecondary, stats }: HeroEditorialProps) {
  const cd = useCountdown();
  const reduced = prefersReducedMotion();
  const y = useScrollY();
  const heroRef = useRef<HTMLElement | null>(null);
  const [heroH, setHeroH] = useState(600);
  const magnetic = useMagnetic<HTMLButtonElement>(7);

  // Days climb from 0 on the first paint; the rest of the clock is exact.
  const dAnim = useCountUp(cd.days, 1100);

  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;
    const measure = () => setHeroH(el.offsetHeight || 600);
    measure();
    window.addEventListener("resize", measure);
    return () => window.removeEventListener("resize", measure);
  }, []);

  const shift = reduced ? 0 : Math.min(y, heroH) * 0.22;
  const fade = Math.max(0, 1 - y / (heroH * 0.9));

  const remaining = stats?.inventory?.remaining ?? null;
  const total = EVENT.inventory.totalStands;

  return (
    <section className="edl-hero" id="top" ref={heroRef}>
      <div className="edl-hero__stage" style={{ transform: `translate3d(0, ${shift}px, 0)` }}>
        <picture>
          {/* AVIF (80 KB) → WebP (159 KB) → the original JPEG. Generated by
              `npm run optimize-images`. */}
          <source srcSet="/assets/hero-illustration.avif" type="image/avif" />
          <source srcSet="/assets/hero-illustration.webp" type="image/webp" />
          <img className="edl-hero__art" src="/assets/hero-illustration.jpg" alt="" draggable={false} />
        </picture>
      </div>
      <div className="edl-hero__scrim" aria-hidden="true" />
      <div className="edl-hero__grain" aria-hidden="true" />
      <div className="edl-hero__glow" aria-hidden="true" />

      <div className="edl__container" style={{ opacity: reduced ? 1 : 0.35 + fade * 0.65 }}>
        <Reveal variant="fade">
          <div className="edl-hero__top">
            <div className="edl-hero__brand">
              <img className="edl-hero__logo" src="/logo.png" alt="FOODERA EXPO 2026" />
              <span>FOODERA</span>
            </div>
            <span className="edl-hero__date">{t(language, "heroEventDate")}</span>
          </div>
        </Reveal>

        <Reveal delay={1} variant="fade">
          <p className="edl__eyebrow edl__eyebrow--live">
            <span className="edl-live-dot" aria-hidden="true" />
            {t(language, "landingKicker")}
          </p>
        </Reveal>

        <RevealWords
          tag="h1"
          className="edl-hero__title"
          text={t(language, "landingTitleEditorial")}
          step={52}
        />

        <Reveal delay={3} variant="lift">
          <p className="edl-hero__sub">{t(language, "landingSubtitle")}</p>
        </Reveal>

        <Reveal delay={4} variant="lift">
          {cd.phase === "before" ? (
            <div className="edl-cd" role="timer" aria-label={t(language, "cdLabel")}>
              <span className="edl-cd__label">{t(language, "cdLabel")}</span>
              <div className="edl-cd__row">
                <Cell value={String(dAnim)} label={t(language, "cdDays")} big />
                <Sep />
                <Cell value={p(cd.hours)} label={t(language, "cdHours")} />
                <Sep />
                <Cell value={p(cd.minutes)} label={t(language, "cdMins")} />
                <Sep />
                <Cell value={p(cd.seconds)} label={t(language, "cdSecs")} accent />
              </div>
            </div>
          ) : (
            <p className="edl-cd__phase">
              <span className="edl-live-dot" aria-hidden="true" />
              {t(language, cd.phase === "live" ? "phaseLive" : "phaseDone")}
            </p>
          )}
        </Reveal>

        <Reveal delay={4}>
          <div className="edl-hero__ctas">
            <button
              type="button"
              ref={magnetic}
              className="edl-btn edl-btn--primary edl-btn--full edl-btn--shine"
              onClick={() => {
                haptics.confirm();
                unlockAudio();
                play("tap");
                onPrimary();
              }}
            >
              {t(language, "landingCtaPrimary")}
              <Icon name="arrow" size={16} />
            </button>
            <button
              type="button"
              className="edl-btn edl-btn--secondary edl-btn--full"
              onClick={() => {
                haptics.tap();
                onSecondary();
              }}
            >
              <Icon name="telegram" size={16} />
              {t(language, "landingCtaSecondary")}
            </button>
            <p className="edl-hero__trust">{t(language, "landingTrust")}</p>
          </div>
        </Reveal>

        <Reveal delay={4} variant="fade">
          <button
            type="button"
            className={`edl-avail${remaining !== null && remaining <= Math.ceil(total * 0.25) ? " edl-avail--tight" : ""}`}
            onClick={() => {
              haptics.tap();
              const el = document.getElementById("packages");
              if (el) window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 64, behavior: reduced ? "auto" : "smooth" });
            }}
          >
            <span className="edl-avail__dot" aria-hidden="true" />
            <span className="edl-avail__txt">
              {remaining === null
                ? t(language, "availTotal").replace("{n}", String(total))
                : t(language, "availLeft").replace("{n}", String(remaining))}
              <em>{EVENT.inventory.label}</em>
            </span>
            <span className="edl-avail__meter" aria-hidden="true">
              <span
                className="edl-avail__fill"
                style={{ width: remaining === null ? "12%" : `${Math.max(8, Math.min(100, ((total - remaining) / total) * 100))}%` }}
              />
            </span>
          </button>
        </Reveal>
      </div>

      <button
        type="button"
        className={`edl-hero__scroll${y > 40 ? " edl-hero__scroll--gone" : ""}`}
        onClick={() => {
          const el = document.getElementById("live");
          if (el) window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 40, behavior: reduced ? "auto" : "smooth" });
        }}
        aria-label={t(language, "scrollHint")}
      >
        <span className="edl-hero__scroll-line" aria-hidden="true" />
        {t(language, "scrollHint")}
      </button>
    </section>
  );
}

function p(n: number): string {
  return String(n).padStart(2, "0");
}

function Sep() {
  return <span className="edl-cd__sep" aria-hidden="true" />;
}

/**
 * A countdown cell. Re-mounting the inner span with `key={value}` is what
 * replays the flip animation on every change — no state machine needed.
 */
function Cell({ value, label, big, accent }: { value: string; label: string; big?: boolean; accent?: boolean }) {
  return (
    <div className={`edl-cd__cell${big ? " edl-cd__cell--big" : ""}`}>
      <span className="edl-cd__box">
        <span className={`edl-cd__val${accent ? " edl-cd__val--gold" : ""}`} key={value}>
          {value}
        </span>
      </span>
      <span className="edl-cd__lbl">{label}</span>
    </div>
  );
}
